// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP6.Models;

#nullable disable

namespace TP6.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP6.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Sections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("School", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Dr. Helen Moore",
                            Name = "Green Valley High",
                            Rating = 4.5,
                            Sections = "Science, Arts, Sports",
                            WebSite = "https://greenvalley.edu"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Mr. John Ellis",
                            Name = "Lakeside Academy",
                            Rating = 3.7999999999999998,
                            Sections = "Mathematics, Humanities"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Ms. Clara Dean",
                            Name = "Mountainview Institute",
                            Rating = 4.9000000000000004,
                            Sections = "Engineering, Computer Science",
                            WebSite = "https://mountainview.edu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
