version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5115:5115"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=postgres_db;Username=postgres_user;Password=password

  db:
    image: postgres:16
    container_name: userRoleDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
